<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <TargetFramework>net10.0-windows7.0</TargetFramework>
  <Nullable>disable</Nullable>
  <UseWPF>true</UseWPF>
  <ImplicitUsings>enable</ImplicitUsings>
  <RootNamespace>Analysis.UI.Common</RootNamespace>
    
  <!-- Common output folder for all Analysis apps -->
  <OutputPath>..\Analysis\</OutputPath>
  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UI.Common\UI.Common.csproj" />
    <ProjectReference Include="..\Analysis.Core\Analysis.Core.csproj" />
    <ProjectReference Include="..\Analysis.DataAccess\Analysis.DataAccess.csproj" />
  </ItemGroup>

  <!-- Embedded sound resources -->
  <ItemGroup>
    <None Remove="Sounds\**\*.wav" />
    <Resource Include="Sounds\**\*.wav" />
  </ItemGroup>

</Project>
