<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <EmbeddedResource Remove="Data\**" />
    <None Remove="Data\**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="protobuf-net" Version="3.2.56" />
	</ItemGroup>

	<PropertyGroup>
		<FathomBuildDir>$(MSBuildProjectDirectory)\..\Fathom\Build\</FathomBuildDir>
	</PropertyGroup>

	<ItemGroup Condition="Exists('$(FathomBuildDir)')">
		<None Include="$(FathomBuildDir)*.dll" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Libs\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="C:\Dev\Kio-Chess\KioChess\DataAccess\..\Fathom\Build\fathomDll.dll" Link="Libs\fathomDll.dll" />
	  <None Update="C:\Dev\Kio-Chess\KioChess\DataAccess\..\Fathom\Build\libgcc_s_seh-1.dll" Link="Libs\libgcc_s_seh-1.dll" />
	  <None Update="C:\Dev\Kio-Chess\KioChess\DataAccess\..\Fathom\Build\libwinpthread-1.dll" Link="Libs\libwinpthread-1.dll" />
	</ItemGroup>

</Project>
