<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <OutputType>WinExe</OutputType>
  <TargetFramework>net10.0-windows7.0</TargetFramework>
  <Nullable>disable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
  <UseWPF>true</UseWPF>
  <RootNamespace>Analysis.Kio.Library</RootNamespace>
    
  <!-- Common output folder for all Analysis apps -->
  <OutputPath>..\Analysis\</OutputPath>
  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  <ApplicationIcon>data_viewer_5is_icon.ico</ApplicationIcon>
</PropertyGroup>

<ItemGroup>
  <Content Include="data_viewer_5is_icon.ico" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analysis.UI.Common\Analysis.UI.Common.csproj" />
  </ItemGroup>

</Project>
